enum ActionTypeKeys {
    GET_PROJECTS_REQUEST="GET_PROJECTS_REQUEST",
    GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS",
    GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE",
    SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT"
}
export default ActionTypeKeys;